#!/bin/sh

# This script is called by ROX-Filer-src.xml. It builds the filer
# against the GTK 2.4 headers, using the gtk-2.4 compatibility environment.

if [ "x$GTK24_HOME" == "x" ]; then
  echo 'Run me like this:'
  echo '0launch ../ROX-Filer-src.xml'
  exit 1
fi
cd `dirname "$0"`
exec "$GTK24_HOME/gtk-2.4" make "$@"
