#!/usr/bin/env perl

chdir "../..";

system "cvs rel .";

open(VER, "ROX-Filer/AppRun --version 2>&1 |") or die "open(): $!";
$line = <VER>;
close(VER);

$line =~ /(\d+)\.(\d+)\.(\d+)$/;

($a, $b, $c) = ($1, $2, $3);

print "Check the manual is up-to-date!\n";
print "Version $a.$b.$c --- OK?\n";

<STDIN> =~ /^[yY]/ or die "OK, fix the version number!\n";

system "cvs tag -F Release-$a-$b-$c";
system "cd ROX-Filer/src/po; ./update-po; ./dist";

chdir;

mkdir "rox-$a.$b.$c", 0775 or warn "mkdir() failed: $!\n";
chdir "rox-$a.$b.$c";

system "cvs -d:pserver:anonymous\@cvs.rox.sourceforge.net:/cvsroot/rox export -r Release-$a-$b-$c rox";

system "cd rox/ROX-Filer/src; autoconf";
system "cp ~/Projects/rox/ROX-Filer/Help/Manual*.ps rox/ROX-Filer/Help";
system "cp -r ~/Projects/rox/ROX-Filer/Messages/*.gmo rox/ROX-Filer/Messages";

system "mv rox/* .";
rmdir "rox";

system "find -name '.cvsignore' | xargs rm";

chdir "..";
system "tar czf rox-$a.$b.$c.tgz rox-$a.$b.$c";
system "rm -r rox-$a.$b.$c";

print "OK, done\n";
