#!/bin/sh

echo Extracting messages from source files...
echo

make ROX-Filer.po

echo
echo Updating all .po files...
echo

for FILE in ../po/*/LC_MESSAGES/ROX-Filer.po; do
	echo -n "Updating '$FILE' translation"
	mv $FILE $FILE.old
	msgmerge $FILE.old ROX-Filer.po > ${FILE};
done
