.TH ROX 1 "October 2000" "Thomas Leonard" ""
.SH NAME
ROX-Filer \- a simple graphical file manager for X11
.SH SYNOPSIS
.B rox
[\fIOPTION\fP]... [\fIFILE\fP]...
.SH DESCRIPTION
.PP
ROX-Filer is a simple and easy to use graphical file manager for X11, the
windowing system used on Unix and Unix-like operating systems.
.PP
It is also the core component of the ROX Desktop:
http://rox.sourceforge.net
.PP
Invoking
.B rox
opens each directory or file listed, or the current working directory
if no arguments are given.
.SH COMMAND-LINE OPTIONS
.TP
\fB\-b\fP, \fB\-\-bottom=PANEL\fP
Open PANEL as a bottom-edge panel.
.TP
\fB\-d\fP, \fB\-\-dir=DIR\fP
Open DIR as directory (not as an application).
.TP
\fB\-h\fP, \fB\-\-help\fP
Print out a command summary.
.TP
\fB\-l\fP, \fB\-\-left=PANEL\fP
Open PANEL as a left-edge panel.
.TP
\fB\-m\fP, \fB\-\-mime-type=FILE\fP
Print the MIME-type that the filer would use for this file to standard
output.
.TP
\fB\-n\fP, \fB\-\-new\fP
Start a new filer, even if one is already running.
.TP
\fB\-o\fP, \fB\-\-override\fP
Override window manager control of panels.
.TP
\fB\-p\fP, \fB\-\-pinboard=PIN\fP
Use pinboard PIN as the pinboard.
.TP
\fB\-r\fP, \fB\-\-right=PANEL\fP
Open PANEL as a right-edge panel.
.TP
\fB\-s\fP, \fB\-\-show=FILE\fP
Open a directory to show FILE.
.TP
\fB\-t\fP, \fB\-\-top=PANEL\fP
Open PANEL as a top-edge panel.
.TP
\fB\-u\fP, \fB\-\-user\fP
Show user name in each window.
.TP
\fB\-v\fP, \fB\-\-version\fP
Print out the version information.
.TP
\fB\-x\fP, \fB\-\-examine=FILE\fP
FILE has changed - re-examine it.

.SH NOTES
The main documentation for ROX-Filer is available by selecting the Help option
in the filer itself.

.SH LICENCE
Copyright (C) 2000 Thomas Leonard.
.br
You may redistribute copies of ROX-Filer under the terms of the GNU General
Public License.

.SH BUGS
Report bugs to <tal197@users.sourceforge.net>.

.SH AUTHORS
ROX-Filer was created by Thomas Leonard, with help from:

Christopher Arndt,
Jens Askengren,
Andrzej Borsuk,
Simon Britnell,
Andrew Clover,
Dmitry Elfimov,
Mattias Engdegard,
Alex Holden,
Bernard Jungen,
James Kermode,
Vincent Ledda,
Vincent Lefevre,
Victor Liu See-le,
Anders Lundmark,
Denis Manente,
Andras Mohari,
Christiansen Merel,
Jimmy Olgeni,
Andy Piper,
Chris Sawer,
Simon Truss,
Jan Wagemakers,
Stephen Watson,
Diego Zamboni,

and many others - the Changes file contains more detailed information!
