#!/bin/sh

if [ $# = 1 ]; then
	OUT=../../Messages/$1.gmo
	msgfmt $1.po -o $OUT && echo Created file $OUT OK
	exit 0
fi

cat << HERE
Usage: 'make-mo <LANG>'
Eg:    'make-mo fr'
	to compile the French translation, fr.po, ready for use.
HERE
