#!/bin/sh

echo Extracting messages from source files...
echo

(cd ..; python po/tips.py;
 xgettext --keyword=_ --keyword=N_ --output=messages.pot *.c tips)

echo
echo Updating all .po files...
echo

for FILE in *.po; do
	echo -n "Updating '$FILE' translation"
	mv "$FILE" "$FILE.old"
	msgmerge "$FILE.old" ../messages.pot > "$FILE";
	rm "$FILE.old"
done
