#!/usr/bin/env bash

set -P
APP_DIR=${0%/*}
if [ "$APP_DIR" = "$0" ] ; then APP_DIR=. ; fi
APP_DIR=`cd $APP_DIR;pwd`; export APP_DIR

DEBUGGER=""
case $1 in
	--debug) shift ; DEBUGGER=gdb ;;
	--compile)
		if [ ! -e $APP_DIR/src/Makefile ] ; then
			echo "ERROR from $0:" >&2
			echo "Cannot compile - source code is missing!" >&2
			exit 1
		fi
		echo "Compiling $APP_DIR... please wait..." >&2
		cd $APP_DIR/src && make clean && make depend \
					&& make && echo Done >&2 && exit 0
		echo Compile failed >&2
		exit 1
esac

PLATFORM=`unset HOSTTYPE; unset OSTYPE; bash -c 'echo $OSTYPE-$HOSTTYPE'`
BIN=$APP_DIR/$PLATFORM/ROX-Filer

if [ -x $BIN ] ; then
  exec $DEBUGGER $BIN $*
else
  echo "ERROR from $0:" >&2
  echo "I cannot find an executable file for your host type ($PLATFORM)." >&2
  echo "Try using the --compile option" >&2
fi
