#!/bin/bash

set -P
APP_DIR=${0%/*}
if [ "$APP_DIR" = "$0" ] ; then APP_DIR=. ; fi
APP_DIR=`cd $APP_DIR;pwd`; export APP_DIR

PLATFORM=`unset HOSTTYPE; unset OSTYPE; bash -c 'echo $OSTYPE-$HOSTTYPE'`

BIN=$APP_DIR/bin/$PLATFORM

if [ -x $BIN ] ; then
  DEBUGGER=""
  case $1 in
  	-d) shift; DEBUGGER=gdb;
  esac
  exec $DEBUGGER $BIN $*
else
  echo "ERROR from $0:" >&2
  echo "I cannot find an executable file for your host type ($PLATFORM)." >&2
  echo "Look inside this application directory for a 'src' directory - if" >&2
  echo "there is one then try running make inside it to create the executable." >&2
fi
